{
 "title": "Minecraft - Monitoring",
 "tags": [ "minecraft" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_entities)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Minecraft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Current MSPT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_tps{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Loaded Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Milliseconds Per Tick",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "MSPT"
    }
   ]
  },
  {
   "title": "Ticks Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minecraft_tps{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Players in {{world}}"
    }
   ]
  },
  {
   "title": "Entities by world",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Entities in {{world}}"
    }
   ]
  },
  {
   "title": "Top entities by type",
   "type": "bargauge",
   "gridPos": { "h": 27, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Entities by spawn group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Loaded chunks in {{world}}"
    }
   ]
  },
  {
   "title": "Loaded chunks per 10 minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minecraft_total_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}[10m])",
     "legendFormat": "Loaded chunks in {{world}}"
    }
   ]
  },
  {
   "title": "JVM Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 52 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=~\"$job\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{job=~\"$job\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=~\"$job\", instance=\"$instance\", area=\"heap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=~\"$job\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{job=~\"$job\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=~\"$job\", instance=\"$instance\", area=\"nonheap\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: G1  Eden",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"$job\", instance=\"$instance\",pool=\"G1 Eden Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"$job\", instance=\"$instance\",pool=\"G1 Eden Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"$job\", instance=\"$instance\",pool=\"G1 Eden Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"$job\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"$job\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"$job\", instance=\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"$job\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"$job\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"$job\", instance=\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 58 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"$job\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"$job\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"$job\", instance=\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: G1 Survivor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"$job\", instance=\"$instance\",pool=\"G1 Survivor Space\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"$job\", instance=\"$instance\",pool=\"G1 Survivor Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"$job\", instance=\"$instance\",pool=\"G1 Survivor Space\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Mem Pool: PS Old",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{job=~\"$job\", instance=\"$instance\",pool=\"G1 Old Gen\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"$job\", instance=\"$instance\",pool=\"G1 Old Gen\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"$job\", instance=\"$instance\",pool=\"G1 Old Gen\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Minecraft logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Log output",
   "type": "logs",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "{container=~\".*minecraft_.*\"} |= ``"
    }
   ]
  }
 ]
}