version: '3.8'
services:
  minecraft:
    image: 'itzg/minecraft-server'
    environment:
      EULA: 'TRUE'
      TYPE: 'PAPER'
      MEMORY: '2G'
      ENABLE_RCON: 'true'
      RCON_PASSWORD: '${RCON_PASSWORD}'
      RCON_PORT: '25575'
    ports:
      - '25565:25565'
      - '25575:25575'
    volumes:
      - '/efs/minecraft:/data'
    restart: 'unless-stopped'
    healthcheck:
      test: 'mc-health'
      interval: '30s'
      timeout: '10s'
      retries: 3
      start_period: '60s'

  rcon:
    image: 'itzg/rcon'
    environment:
      RWA_PASSWORD: '${RCON_PASSWORD}'
      RWA_HOST: 'minecraft'
      RWA_PORT: '25575'
    depends_on:
      - 'minecraft'

  monitor:
    image: 'python:3.12-alpine'
    volumes:
      - '/efs/minecraft:/data'
      - './scripts:/scripts'
    environment:
      RCON_HOST: 'minecraft'
      RCON_PORT: '25575'
      RCON_PASSWORD: '${RCON_PASSWORD}'
      INACTIVITY_SHUTDOWN_MINUTES: '${INACTIVITY_SHUTDOWN_MINUTES:-30}'
    command: 'sh -c "apk add --no-cache aws-cli && pip install mcrcon boto3 requests && while true; do python /scripts/check_activity.py; sleep 60; done"'
    depends_on:
      - 'minecraft'
      - 'rcon'