name: Deploy CloudFormation Templates

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation template
        run: |
          aws cloudformation deploy \
            --template-file aws/cloudformation/ec2-minecraft-server.yml \
            --stack-name minecraft-server \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              ServerName=minecraft-server \
              MinecraftBucket=${{ secrets.MINECRAFT_BUCKET }} \
              MinecraftPort=25565 \
              InactivityShutdownMinutes=30 \
              TerminateAfterDays=7 \
              InstanceType=t4g.small
