AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a secure S3 bucket for Minecraft server configuration and artifacts'

Resources:
  MinecraftBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Delete'
    UpdateReplacePolicy: 'Retain'
    Properties:
      BucketName: !Sub '${AWS::StackName}-minecraft'
      VersioningConfiguration:
        Status: 'Enabled'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
            BucketKeyEnabled: true
      LoggingConfiguration:
        DestinationBucketName: !Ref 'AccessLogsBucket'
        LogFilePrefix: 'minecraft-bucket-logs/'
      LifecycleConfiguration:
        Rules:
          - Id: 'DeleteOldVersions'
            Status: 'Enabled'
            NoncurrentVersionExpiration:
              NoncurrentDays: 90
          - Id: 'AbortIncompleteUploads'
            Status: 'Enabled'
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  AccessLogsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Delete'
    UpdateReplacePolicy: 'Retain'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: 'Enabled'
      LifecycleConfiguration:
        Rules:
          - Id: 'DeleteOldLogs'
            Status: 'Enabled'
            ExpirationInDays: 365
          - Id: 'AbortIncompleteUploads'
            Status: 'Enabled'
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  MinecraftBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref 'MinecraftBucket'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'EnforceSSLOnly'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${MinecraftBucket.Arn}/*'
              - !GetAtt 'MinecraftBucket.Arn'
            Condition:
              Bool:
                'aws:SecureTransport': false
          - Sid: 'EnforceSecureCommunication'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${MinecraftBucket.Arn}/*'
              - !GetAtt 'MinecraftBucket.Arn'
            Condition:
              NumericLessThan:
                's3:TlsVersion': 1.2

  AccessLogsBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref 'AccessLogsBucket'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'EnforceSSLOnly'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${AccessLogsBucket.Arn}/*'
              - !GetAtt 'AccessLogsBucket.Arn'
            Condition:
              Bool:
                'aws:SecureTransport': false
          - Sid: 'EnforceSecureCommunication'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${AccessLogsBucket.Arn}/*'
              - !GetAtt 'AccessLogsBucket.Arn'
            Condition:
              NumericLessThan:
                's3:TlsVersion': 1.2

Outputs:
  BucketName:
    Description: 'Name of the created S3 bucket'
    Value: !Ref 'MinecraftBucket'
    Export:
      Name: !Sub '${AWS::StackName}-bucket-name'

  BucketArn:
    Description: 'ARN of the created S3 bucket'
    Value: !GetAtt 'MinecraftBucket.Arn'
    Export:
      Name: !Sub '${AWS::StackName}-bucket-arn'
