---
name: 'Deploy S3 Buckets'

on:
  workflow_run:
    workflows: ["Static Code Tests"]
    types:
      - 'completed'
    branches: ['main']

env:
  LOG_STACK_NAME: 'rubik-logging'
  BUCKET_STACK_NAME: 'rubik-deploy'
  USE_LOG_BUCKET: 'true'

permissions:
  id-token: 'write'
  contents: 'read'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    if: "${{ github.event.workflow_run.conclusion == 'success' }}"
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'

      - name: 'Configure AWS credentials'
        uses: 'aws-actions/configure-aws-credentials@v4'
        with:
          role-to-assume: '${{ secrets.AWS_ROLE_ARN }}'
          aws-region: '${{ secrets.AWS_REGION }}'

      - name: 'Deploy Access Logs Bucket'
        if: "${{ env.USE_LOG_BUCKET == 'true' }}"
        uses: 'aws-actions/aws-cloudformation-github-deploy@v1'
        with:
          name: '${{ env.LOG_STACK_NAME }}'
          template: 'aws/cloudformation/s3-log-bucket.yml'
          no-fail-on-empty-changeset: '1'

      - name: 'Deploy Minecraft Bucket'
        uses: 'aws-actions/aws-cloudformation-github-deploy@v1'
        with:
          name: '${{ env.BUCKET_STACK_NAME }}'
          template: 'aws/cloudformation/s3-bucket.yml'
          parameter-overrides: |
            AccessLogsStackName=${{ env.USE_LOG_BUCKET == 'true' && env.LOG_STACK_NAME || 'no-set' }}
          no-fail-on-empty-changeset: '1'
